# Generated by Django 6.0.7 on 2026-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_userprofile_bio_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ar', 'Arabic'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ru', 'Russian')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'India (IST, UTC+5:30)'), ('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'New York (EST/EDT, UTC-5/-4)'), ('America/Chicago', 'Chicago (CST/CDT, UTC-6/-5)'), ('America/Denver', 'Denver (MST/MDT, UTC-7/-6)'), ('America/Los_Angeles', 'Los Angeles (PST/PDT, UTC-8/-7)'), ('Europe/London', 'London (GMT/BST, UTC+0/+1)'), ('Europe/Paris', 'Paris (CET/CEST, UTC+1/+2)'), ('Europe/Berlin', 'Berlin (CET/CEST, UTC+1/+2)'), ('Asia/Dubai', 'Dubai (GST, UTC+4)'), ('Asia/Singapore', 'Singapore (SGT, UTC+8)'), ('Asia/Tokyo', 'Tokyo (JST, UTC+9)'), ('Australia/Sydney', 'Sydney (AEST/AEDT, UTC+10/+11)'), ('Pacific/Auckland', 'Auckland (NZST/NZDT, UTC+12/+13)')], default='Asia/Kolkata', max_length=50),
        ),
    ]
