# Generated by Django 6.0.7 on 2026-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_venue_event_banner_event_end_time_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit_participants',
            field=models.BooleanField(default=True),
        ),
    ]
