# Generated by Django 6.0.7 on 2026-08-10 10:32

from django.db import migrations, models


def set_unlimited(apps, schema_editor):
    Event = apps.get_model('event', 'Event')
    Event.objects.update(limit_participants=False)


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_update_defaults'),
    ]

    operations = [
        migrations.RunPython(set_unlimited, migrations.RunPython.noop),
    ]
